export const Underlinetext = [
    {
        title: "Underliner Text Converter",
        sentence: "Do you need to find an easy way to quickly draw attention to a piece of text? Then you should really take a look at our underline text formatting tool. Text editing is a time consuming process, but this underline text program gives you the simplest, quickest, and easiest way to make the adjustments as you would have wanted. With an underline text editor, you can add that all important emphasis to any piece of text that needs changing. Remove the stress and the challenge of text editing with an underline text adjustment that can really make the text stand out for the right reasons.",
        subtitle: "If you ever need to format and adjust your content, then using underline text is a very wise choice. This looks great, adds in some much-needed detail, and can freshen up the entire look and feel of a piece of content. You can also easily draw attention to key numbers, statements, or facts that are listed within your content. An underline text section is one that should immediately and instantly draw attention. It can help to create emphasis, to encourage people to read that section, or simply make it easier to stand out.",
        text: "Instead of having to edit all of the content on your own, though, our underline text editor makes the job that little bit easier. The biggest thing you can do for yourself when it comes to editing and improving content is to take a look at the best way to format each section.",
        textdata: 'When you feel like the addition of some underline text could be useful, copy in what you need to our left-hand side box. This will then automatically show the underline text on the right-hand box, ready for you to copy and/or download.'
    },
    {
        title: "How does it work?",
        sentence: "Simply write up the text that you want converting (or simply paste it in, if you already have it on hand) in the first panel you see on the left and then you will see that the text is automatically getting generated by the converter on the next panel. You will then be able to go ahead and copy that specific underlined text and paste it wherever you like.",
        subtitle: "If you are looking for an example of italic text then please see below:",
        data: "This is an example of underline text",
        textdata: 'Do you think we can improve on the underline text converter further? Send us a message as we’d love to hear your suggestions. We read every single one at the Convert Case team.'
    }
]